version: "3.9"

services:
  bot:
    build: .
    container_name: gigachat_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python main.py

  redis:
    image: redis:7-alpine
    container_name: gigachat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
